### ISSUE TITLE
Investigar tests en Java

### ISSUE THREAD

**Issue by apiorno** [emmanuelalbe/blog#1]
- Investigar como hacer tests en Java
- investigar sobre TDD

**Comment by emmanuelalbe** [comment]
Hace dos días que estoy tratando de configurar el Junit y estoy teniendo problemas para correrlo manualmente.. Estoy tratando de solucionarlo para poder practicar lo aprendido en los videos, aun así no lo he podido finalizar la capacitación

**Comment by emmanuelalbe** [comment]
Buenos días amigo, estuve con unos inconvenientes para incorporar el testing neetbeens, de todos modos hoy estuve mirando videos y chateando con chat gpt para poder avanzar con la capacitación, por ende decidí trabajan con Marven, no se que diferencia hay por el momento, mas adelante me adentrare en el tema.. pero la idea es seguir avanzando con la capacitacion / practica del Testing !
